openapi: 3.0.3
info:
  title: onecx-demo-bff
  description: Backend-For-Frontend (BFF) services for onecx-demo. This API provides endpoints to manage demo items.
  version: 1.0.0
servers:
  - url: http://onecx-demo-bff:8080/
tags:
  - name: product
    description: Managing Product items
  - name: category
    description: Managing Category items
paths: {}
components:
  schemas:
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
    OffsetDateTime:
      format: date-time
      type: string
      example: 2022-03-10T12:15:50-04:00
    Product:
      type: object
      required:
        - id
      properties:
        modificationCount:
          type: integer
          format: int32
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
          readOnly: true
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
          readOnly: true
        id:
          type: string
          readOnly: true
        name:
          type: string
        category:
          type: Object
          $ref: '#/components/schemas/Category'
    Category:
      type: object
      required:
        - id
      properties:
        modificationCount:
          type: integer
          format: int32
        creationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        creationUser:
          type: string
          readOnly: true
        modificationDate:
          $ref: '#/components/schemas/OffsetDateTime'
        modificationUser:
          type: string
          readOnly: true
        id:
          type: string
          readOnly: true
        # "ACTION E: Add entity properties"
