name: documentation
on:
  workflow_dispatch:
jobs:
  documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '25'
      - name: Run workflow command
        run: mvn -B -ntp -DskipTests package
